server:
  port: 9092

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      enabled: false  #false because error in postman An expected CSRF token cannot be found
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userServiceFallback

        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
          filters:
            - name: CircuitBreaker
              args:
                name: contact-service
                fallbackuri: forward:/contactServiceFallback

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
    #web-application-type: reactive


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

jwt:
  secret: upender@gmail.com

security:
  ignored=/**:
  enable-csrf: false



